Clean footer
RogeSocial/cinema-project pull request #66
Opened 2023-01-26 15:38 UTC by rimdagic

2023-01-26 18:21 UTC, Rufat-J requested changes
Taggar ser bra ut, dock är det extremt små check ikoner som dyker upp mitt på skärmen i tickets page. samt error i console: 

Warning: The tag <adress> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    at adress
    at div
    at footer
    at default
    at App

2023-01-26 22:24 UTC, rimdagic commented
Tack jag hade inte sett det, har bytt till ett element som inte genererar fel. De små checksen i tickets är nog elementen där datumet dyker upp när man valt datum och elementet där movie-cardsen dyker upp. De är även där i main, om det var dem du menade.

2023-01-27 08:36 UTC, RogeSocial approved these changes

2023-01-27 08:36 UTC, thalassa111 approved these changes
Looks good now

2023-01-27 08:37 UTC, jfMoller approved these changes
ok

2023-01-27 08:37 UTC, merged